<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DP6GTV0" name="用户管理系统测试用例" tests="2" failures="1" timestamp="11 Jan 2020 07:09:35 GMT" time="1.248" errors="0">
  <testcase name="LoginTrue" time="1.181" classname="com.Test.cases.LoginTest"/>
  <testcase name="AddUser" time="0.026" classname="com.Test.cases.AddUserTest">
    <failure type="java.lang.RuntimeException" message="{&amp;quot;result&amp;quot;:0,&amp;quot;data&amp;quot;:{},&amp;quot;msg&amp;quot;:&amp;quot;账号已经被注册&amp;quot;,&amp;quot;timestamp&amp;quot;:1578726574}">
      <![CDATA[java.lang.RuntimeException: {"result":0,"data":{},"msg":"账号已经被注册","timestamp":1578726574}
	at com.Test.cases.AddUserTest.AddUser(AddUserTest.java:44)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- AddUser -->
</testsuite> <!-- 用户管理系统测试用例 -->
